name: actions
on:
  push:
    paths:
      - 'update.sh'
      - '.github/workflows/actions.yml'
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: 'noninteractive'

jobs:
  debian-debootstrap-ports:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        QEMU_VER: [v9.0.2-1]
        DOCKER_REPO: [docker.io/polyarch/debian-debootstrap-ports]
        VERSION: [sid, experimental, unreleased]
        UNAME_ARCH: [alpha, hppa, loong64, m68k, ppc64, sh4, sparc64]
        include:
          - {ARCH: alpha,       QEMU_ARCH: alpha,       UNAME_ARCH: alpha}
          - {ARCH: hppa,        QEMU_ARCH: hppa,        UNAME_ARCH: hppa}
          - {ARCH: m68k,        QEMU_ARCH: m68k,        UNAME_ARCH: m68k}
          - {ARCH: loongarch64, QEMU_ARCH: loongarch64, UNAME_ARCH: loongarch64}
          - {ARCH: ppc64,       QEMU_ARCH: ppc64,       UNAME_ARCH: ppc64}
          - {ARCH: sh4,         QEMU_ARCH: sh4,         UNAME_ARCH: sh4}
          - {ARCH: sparc64,     QEMU_ARCH: sparc64,     UNAME_ARCH: sparc64}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          sudo apt update && sudo apt install -y qemu-user-static debootstrap
          ./update.sh -a ${{ matrix.ARCH }} -v ${{ matrix.VERSION }} -q ${{ matrix.QEMU_ARCH }} -u ${{ matrix.QEMU_VER }} -d ${{ matrix.DOCKER_REPO }} -o ${{ matrix.UNAME_ARCH }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Docker images
        run: |
          docker push -a ${{ matrix.DOCKER_REPO }}
