name: actions
on:
  push:
    paths:
      - 'update.sh'
      - '.github/workflows/actions.yml'
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: 'noninteractive'
  BOOTSTRAP_VERSION: [v000]
  DOCKER_REPO: [polyarch/debian-ports]
  QEMU_VER: [v9.0.2-2]
  OS: [linux]

jobs:
  debian-ports-docker-arch-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        VERSION: [sid]
        UNAME_ARCH: [hppa, loong64, m68k, ppc, ppc64, sh4, sparc64]
        include:
          - {ARCH: hppa,        QEMU_ARCH: hppa,        UNAME_ARCH: hppa}
          - {ARCH: loong64,     QEMU_ARCH: loongarch64, UNAME_ARCH: loong64}
          - {ARCH: m68k,        QEMU_ARCH: m68k,        UNAME_ARCH: m68k}
          - {ARCH: powerpc,     QEMU_ARCH: ppc,         UNAME_ARCH: ppc}
          - {ARCH: ppc64,       QEMU_ARCH: ppc64,       UNAME_ARCH: ppc64}
          - {ARCH: sh4,         QEMU_ARCH: sh4,         UNAME_ARCH: sh4}
          - {ARCH: sparc64,     QEMU_ARCH: sparc64,     UNAME_ARCH: sparc64}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          sudo apt update && sudo apt install -y qemu-user-static debootstrap
          ./update.sh -a ${{ matrix.ARCH }} -b ${BOOTSTRAP_VERSION} -v ${{ matrix.VERSION }} -q ${{ matrix.QEMU_ARCH }} -u ${QEMU_VER} -d ${DOCKER_REPO} -o ${{ matrix.UNAME_ARCH }}
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Docker images
        if: github.ref == 'refs/heads/main'
        run: |
          docker push -a ${{ matrix.DOCKER_REPO }}

  debian-ports-docker-arch-combine:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Combine into One Big Union
        run: |
           docker manifest create ${DOCKER_REPO}:${BOOTSTRAP_VERSION} \
                            --amend ${BOOTSTRAP_VERSION}-${OS}-hppa \
                            --amend ${BOOTSTRAP_VERSION}-${OS}-loong64 \
                            --amend ${BOOTSTRAP_VERSION}-${OS}-m68k \
                            --amend ${BOOTSTRAP_VERSION}-${OS}-ppc \
                            --amend ${BOOTSTRAP_VERSION}-${OS}-ppc64 \
                            --amend ${BOOTSTRAP_VERSION}-${OS}-sh4 \
                            --amend ${BOOTSTRAP_VERSION}-${OS}-sparc64
      - name: Inspect the combination
        run: |
            docker manifest inspect ${DOCKER_REPO}:${BOOTSTRAP_VERSION}
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Docker polyarch manifest
        if: github.ref == 'refs/heads/main'
        run: |
          docker manifest push
